# Generated by Django 4.1.4 on 2026-02-22 16:00

from django.conf import settings
from django.db import migrations
from django.utils import timezone


def seed_default_free_plan_and_backfill(apps, schema_editor):
    Plan = apps.get_model("subscriptions", "Plan")
    UserSubscription = apps.get_model("subscriptions", "UserSubscription")
    CustomUser = apps.get_model("accounts", "CustomUser")
    ScrapingUrlQuota = apps.get_model("quotas", "ScrapingUrlQuota")
    OfferQuota = apps.get_model("quotas", "OfferQuota")

    free_plan, _ = Plan.objects.get_or_create(
        slug="free",
        defaults={
            "name": "Free",
            "max_urls": settings.QUOTA_FREE_TIER_MAX_URLS,
            "max_offers_per_target": settings.QUOTA_FREE_TIER_OFFERS_PER_TARGET,
            "is_default": True,
            "is_active": True,
            "display_order": 0,
        },
    )

    fields_to_update = []
    if not free_plan.is_default:
        free_plan.is_default = True
        fields_to_update.append("is_default")
    if free_plan.display_order != 0:
        free_plan.display_order = 0
        fields_to_update.append("display_order")
    if not free_plan.is_active:
        free_plan.is_active = True
        fields_to_update.append("is_active")
    if free_plan.max_urls != settings.QUOTA_FREE_TIER_MAX_URLS:
        free_plan.max_urls = settings.QUOTA_FREE_TIER_MAX_URLS
        fields_to_update.append("max_urls")
    if free_plan.max_offers_per_target != settings.QUOTA_FREE_TIER_OFFERS_PER_TARGET:
        free_plan.max_offers_per_target = settings.QUOTA_FREE_TIER_OFFERS_PER_TARGET
        fields_to_update.append("max_offers_per_target")
    if fields_to_update:
        free_plan.save(update_fields=[*fields_to_update, "updated_at"])

    now = timezone.now()
    subscriptions_to_create = []

    existing_active_user_ids = set(UserSubscription.objects.filter(is_active=True).values_list("user_id", flat=True))
    for user in CustomUser.objects.iterator(chunk_size=500):
        if user.id in existing_active_user_ids:
            continue
        subscriptions_to_create.append(
            UserSubscription(
                user_id=user.id,
                plan_id=free_plan.id,
                started_at=now,
                expires_at=None,
                is_active=True,
            )
        )

    if subscriptions_to_create:
        UserSubscription.objects.bulk_create(subscriptions_to_create, batch_size=500)

    ScrapingUrlQuota.objects.update(max_urls=free_plan.max_urls)
    OfferQuota.objects.update(
        max_offers_per_period=free_plan.max_offers_per_target,
        is_free_tier=True,
    )


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0001_initial"),
        ("quotas", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_default_free_plan_and_backfill, noop_reverse),
    ]
