# Generated by Django 3.1.6 on 2021-02-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrappingtarget",
            name="name",
            field=models.CharField(default="name", max_length=100),
        ),
    ]
