# Generated by Django 3.1.7 on 2021-02-28 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_notificationconfig"),
        ("offers", "0003_auto_20210215_2013"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offer",
            options={"verbose_name": "Offer", "verbose_name_plural": "Offers"},
        ),
        migrations.AlterModelOptions(
            name="scrappingtarget",
            options={
                "verbose_name": "Scrapping target",
                "verbose_name_plural": "Scrapping targets",
            },
        ),
        migrations.RemoveField(
            model_name="scrappingtarget",
            name="notification_channel",
        ),
        migrations.AddField(
            model_name="scrappingtarget",
            name="notification_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="notifications.notificationconfig",
                verbose_name="Notification channel",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Closed at"),
        ),
        migrations.AlterField(
            model_name="offer",
            name="price",
            field=models.IntegerField(blank=True, null=True, verbose_name="Price"),
        ),
        migrations.AlterField(
            model_name="offer",
            name="published_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Published at"
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="offers.scrappingtarget",
                verbose_name="Target",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="scrappingtarget",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
    ]
