# Generated by Django 3.1.8 on 2022-01-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0005_scrappingtarget_enable_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrappingtarget",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Defines whether this target should be scrapped",
                verbose_name="Is active",
            ),
        ),
    ]
