# Generated by Django 3.1.8 on 2022-01-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0006_scrappingtarget_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="main_image_url",
            field=models.URLField(blank=True, verbose_name="Main image's URL"),
        ),
    ]
