# Generated by Django 3.1.8 on 2022-01-07 16:09

from django.db import migrations, models

import shargain.offers.models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0007_offer_main_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="source_html",
            field=models.FileField(
                blank=True,
                upload_to=shargain.offers.models.get_offer_source_html_path,
                verbose_name="Source HTML",
            ),
        ),
    ]
