# Generated by Django 3.1.8 on 2022-01-14 21:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0008_offer_source_html"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="last_check_at",
            field=models.DateTimeField(
                default=django.utils.timezone.localtime,
                help_text="Time of last offer check",
                verbose_name="Last check at",
            ),
        ),
    ]
