# Generated by Django 3.1.14 on 2022-01-16 10:49

import django.contrib.postgres.fields
import django_better_admin_arrayfield
from django.db import migrations, models


def migrate_char_to_array(apps, schema_editor):
    ScrappingTarget = apps.get_model("offers", "ScrappingTarget")
    for target in ScrappingTarget.objects.all():
        target.list_url = [target.url]
        target.save(update_fields=["list_url"])


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0010_auto_20220115_1709"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrappingtarget",
            name="list_url",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.URLField(max_length=1024),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.RunPython(migrate_char_to_array, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="scrappingtarget",
            name="url",
        ),
        migrations.RenameField(
            model_name="scrappingtarget", old_name="list_url", new_name="url"
        ),
    ]
