# Generated by Django 4.1.4 on 2023-04-13 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0012_scrapingurl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="scrapingurl",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="scrapingurl",
            name="scraping_target",
            field=models.ForeignKey(
                help_text="Group of scraping URLs",
                on_delete=django.db.models.deletion.CASCADE,
                to="offers.scrappingtarget",
                verbose_name="Scraping target",
            ),
        ),
        migrations.AlterField(
            model_name="scrappingtarget",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
