# Generated by Django 4.1.4 on 2025-07-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0013_alter_offer_id_alter_scrapingurl_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="list_url",
            field=models.URLField(
                blank=True,
                help_text="URL of the page where this offer was found",
                max_length=1024,
                verbose_name="List URL",
            ),
        ),
    ]
