# Generated by Django 4.1.4 on 2025-08-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0015_scrappingtarget_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapingurl",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Defines whether this url should be scrapped",
                verbose_name="Is active",
            ),
        ),
    ]
