# Generated by Django 4.1.4 on 2025-09-04 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0016_scrapingurl_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapingCheckin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("offers_count", models.PositiveIntegerField()),
                ("new_offers_count", models.PositiveIntegerField()),
                (
                    "scraping_url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="offers.scrapingurl",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scraping checkin",
                "verbose_name_plural": "Scraping checkins",
            },
        ),
    ]
