# Generated by Django 4.1.4 on 2026-01-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0017_scrapingcheckin"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapingurl",
            name="filters",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Filter rules to apply before sending notifications",
                null=True,
                verbose_name="Notification filters",
            ),
        ),
    ]
