# Generated by Django 4.1.4 on 2025-10-10 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0017_scrapingcheckin"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfferQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "max_offers_per_period",
                    models.PositiveIntegerField(
                        help_text="Maximum number of offers allowed in the period",
                        verbose_name="Max offers per period",
                    ),
                ),
                (
                    "used_offers_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of offers used in the current period",
                        verbose_name="Used offers count",
                    ),
                ),
                (
                    "period_start",
                    models.DateTimeField(
                        help_text="Start of the current quota period",
                        verbose_name="Period start",
                    ),
                ),
                (
                    "period_end",
                    models.DateTimeField(
                        help_text="End of the current quota period",
                        verbose_name="Period end",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offer_quotas",
                        to="offers.scrappingtarget",
                        verbose_name="Target",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offer quota",
                "verbose_name_plural": "Offer quotas",
            },
        ),
    ]
