# Generated by Django 4.1.4 on 2026-05-01 17:48

from django.db import migrations, models

import shargain.offers.models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0018_add_filters_to_scraping_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=shargain.offers.models.get_default_metadata,
                help_text=(
                    "Metadata for the offer. Use 'extra' key for unstructured scraper data. "
                    "Root level is reserved for official contract fields."
                ),
                verbose_name="Metadata",
            ),
        ),
    ]
