# Generated by Django 4.1.4 on 2025-10-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0018_offerquota"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offerquota",
            name="max_offers_per_period",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of offers allowed in the period",
                null=True,
                verbose_name="Max offers per period",
            ),
        ),
        migrations.AlterField(
            model_name="offerquota",
            name="period_end",
            field=models.DateTimeField(
                blank=True,
                help_text="End of the current quota period",
                null=True,
                verbose_name="Period end",
            ),
        ),
    ]
