# Generated by Django 4.1.4 on 2026-05-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0019_offer_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapingurl",
            name="show_location_map_in_notifications",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "If True, a Google Maps link will be appended to Telegram notifications for offers from this URL."
                ),
                verbose_name="Show location map in notifications",
            ),
        ),
    ]
