# Generated by Django 4.1.4 on 2026-05-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0020_scrapingurl_show_location_map_in_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapingurl",
            name="waypoints",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text='List of waypoints. Format: [{"name": ..., "lat": ..., "lon": ...}]',
                null=True,
                verbose_name="Waypoints",
            ),
        ),
    ]
