# Generated by Django 4.1.4 on 2026-06-28 20:42

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0021_scrapingurl_waypoints"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="offer",
            index=django.contrib.postgres.indexes.HashIndex(fields=["url"], name="offer_url_hash_idx"),
        ),
    ]
