# Generated by Django 4.1.4 on 2026-07-25 16:55

from django.db import migrations

import shargain.offers.fields


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0022_add_offer_url_hash_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapingurl",
            name="notification_fields",
            field=shargain.offers.fields.PydanticField(
                blank=True,
                default=None,
                help_text=("Field names from plugins to include in notification messages"),
                null=True,
                pydantic_model=("shargain.offers.schemas.field_plugin.NotificationFieldsSelection"),
                verbose_name="Notification fields",
            ),
        ),
    ]
