# Generated by Django 4.1.4 on 2026-09-22 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("offers", "0023_scrapingurl_notification_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfferLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "liker_label",
                    models.CharField(blank=True, max_length=255, verbose_name="Liker label"),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="offers.offer",
                        verbose_name="Offer",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offer_likes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offer like",
                "verbose_name_plural": "Offer likes",
                "ordering": ["offer_id", "pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="offerlike",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("owner__isnull", False),
                    models.Q(("liker_label", ""), _negated=True),
                    _connector="OR",
                ),
                name="offer_like_has_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="offerlike",
            constraint=models.UniqueConstraint(
                condition=models.Q(("owner__isnull", False)),
                fields=("offer", "owner"),
                name="uniq_offer_like_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="offerlike",
            constraint=models.UniqueConstraint(
                condition=models.Q(("liker_label", ""), _negated=True),
                fields=("offer", "liker_label"),
                name="uniq_offer_like_label",
            ),
        ),
    ]
