# Generated by Django 5.2.17 on 2026-09-24 14:49

import django_better_admin_arrayfield.models.fields
from django.db import migrations

import shargain.commons.models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0023_scrapingurl_notification_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="list_url",
            field=shargain.commons.models.HttpURLField(
                blank=True,
                help_text="URL of the page where this offer was found",
                max_length=1024,
                verbose_name="List URL",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="main_image_url",
            field=shargain.commons.models.HttpURLField(blank=True, max_length=1024, verbose_name="Main image's URL"),
        ),
        migrations.AlterField(
            model_name="offer",
            name="url",
            field=shargain.commons.models.HttpURLField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="scrapingurl",
            name="url",
            field=shargain.commons.models.HttpURLField(
                help_text="Target URL to one of the supported sites",
                max_length=1024,
                verbose_name="Target URL",
            ),
        ),
        migrations.AlterField(
            model_name="scrappingtarget",
            name="url",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=shargain.commons.models.HttpURLField(max_length=1024),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
