# Generated by Django 4.1.4 on 2025-08-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegram", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramregistertoken",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Optional name to recognize tokens",
                max_length=100,
            ),
        ),
    ]
