services:
  jaeger:
    image: jaegertracing/jaeger:2.19.0
    restart: always
    ports:
      - "4318:4318"
      - "16686:16686"
    networks:
      - traefik

networks:
  traefik:
    external: true
