---
# tasks file for locale

- name: include assert.yml
  include_tasks: assert.yml
  run_once: yes

- name: install requirements
  package:
    name: "{{ locale_requirements }}"
    state: present

- name: configure locale.conf
  template:
    src: locale.conf.j2
    dest: "{{ locale_configuration_file }}"
    mode: "0644"
  notify:
    - localectl set-locale

- name: set timezone
  timezone:
    name: "{{ locale_timezone }}"
