# Generated by Django 4.1.4 on 2025-09-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_registertoken_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="tier",
            field=models.CharField(default="free", max_length=50),
        ),
    ]
