# Generated by Django 4.1.4 on 2025-10-10 16:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_customuser_tier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="tier",
        ),
    ]
