name: CI
on: [push, pull_request]
env:
  POSTGRES_HOST: localhost
  POSTGRES_DB: github_actions
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  TELEGRAM_BOT_TOKEN: "111:faketoken"
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: github_actions
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: psycopg2 prerequisites
        run: sudo apt-get install libpq-dev
      - name: Install dependencies
        run: uv sync --frozen
      - name: Run tests
        run: uv run pytest shargain -n 2
  quality:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        tox-env: [ruff-lint, ruff-format, mypy]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox-uv
      - run: |
            echo TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN >> .env
            cat .env
      - name: Test with tox
        run: tox -e ${{ matrix.tox-env }}
