name: Deploy application
on:
  workflow_dispatch:
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: willhallonline/ansible:2.12.2-ubuntu-20.04
    environment: production
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      ANSIBLE_VAULT_PASSWORD_FILE: vault
      ANSIBLE_HOST_KEY_CHECKING: False
      ANSIBLE_STRATEGY_PLUGINS: $SITE_PACKAGES/ansible_mitogen/plugins/strategy
      ANSIBLE_NO_LOG: True
    defaults:
      run:
        working-directory: deployment/ansible-play-shargain
    steps:
      - uses: actions/checkout@v1
      - name: Create vault file
        run: "echo $VAULT_PASSOWRD > $ANSIBLE_VAULT_PASSWORD_FILE"
        env:
          VAULT_PASSOWRD: ${{ secrets.VAULT_PASSWORD }}
      - name: Setup SSH Keys and known_hosts
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh-add -
      - name: Register python site packages
        run: echo "SITE_PACKAGES=$(python3 -c 'import site; print(site.getsitepackages()[0])')" >> $GITHUB_ENV
      - name: Install ruby dependency
        run: |
          apt-get update
          apt-get install -y libyaml-dev
      - name: Wait for all other check to complete
        uses: lewagon/wait-on-check-action@v1.1.1
        with:
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          running-workflow-name: deploy
        env:
          ImageOS: ubuntu20 # required because in container there is no os_release file
      - name: Run deployment check
        run: ansible-playbook -i inventory.txt shargain.yml -t docker_container -e "_docker_tag=${{ github.sha }}"

