name: Deploy application
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: willhallonline/ansible:2.12.2-ubuntu-20.04
    environment: production
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      SSH_CONFIG_FILE: /tmp/ssh_config
      ANSIBLE_VAULT_PASSWORD_FILE: vault
      ANSIBLE_HOST_KEY_CHECKING: False
      ANSIBLE_STRATEGY_PLUGINS: $SITE_PACKAGES/ansible_mitogen/plugins/strategy
      ANSIBLE_NO_LOG: True
    defaults:
      run:
        working-directory: deployment/ansible-play-shargain
    steps:
      - uses: actions/checkout@v4
      - name: Create vault file
        run: "echo $VAULT_PASSOWRD > $ANSIBLE_VAULT_PASSWORD_FILE"
        env:
          VAULT_PASSOWRD: ${{ secrets.VAULT_PASSWORD }}
      - name: Setup SSH Keys and known_hosts
        run: |
          # Start SSH agent
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh-add -
          # Create SSH config file from environment variable
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_CONFIG }}" > $SSH_CONFIG_FILE
          chmod 600 $SSH_CONFIG_FILE
      - name: Extract branch name
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Deploy via SSH
        run: >
          ssh -q -F $SSH_CONFIG_FILE prod "
            cd shargain &&
            export IMAGE_TAG=${{ env.BRANCH_NAME }} &&
            docker compose up -d --pull always"
