# Generated by Django 3.1.6 on 2021-02-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationChannel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "platform",
                    models.CharField(
                        choices=[("discord", "Discord"), ("telegram", "Telegram")],
                        max_length=200,
                    ),
                ),
                ("webhook_url", models.URLField(blank=True)),
                ("token", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
