# Generated by Django 3.1.7 on 2021-02-28 12:59

from django.db import migrations, models

from shargain.notifications.models import NotificationChannelChoices


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "channel",
                    models.CharField(
                        choices=NotificationChannelChoices.choices,
                        max_length=200,
                        verbose_name="Channel",
                    ),
                ),
                (
                    "webhook_url",
                    models.URLField(blank=True, verbose_name="Webhook url"),
                ),
                (
                    "token",
                    models.CharField(blank=True, max_length=100, verbose_name="Token"),
                ),
                (
                    "chatid",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Chat ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification channel",
                "verbose_name_plural": "Notification channels",
            },
        ),
    ]
