# Generated by Django 3.1.7 on 2021-02-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "channel",
                    models.CharField(
                        choices=[("discord", "Discord"), ("telegram", "Telegram")],
                        max_length=200,
                    ),
                ),
                ("webhook_url", models.URLField(blank=True)),
                ("token", models.CharField(blank=True, max_length=100)),
                ("chatid", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "Notification channel",
                "verbose_name_plural": "",
            },
        ),
    ]
