# Generated by Django 3.1.7 on 2021-02-28 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_notificationconfig"),
        ("offers", "0004_auto_20210228_1359"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NotificationChannel",
        ),
    ]
