# Generated by Django 4.1.4 on 2023-05-01 21:07

from django.db import migrations, models

import shargain.notifications.models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0004_rename_token_notificationconfig__token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationconfig",
            name="register_token",
            field=models.CharField(
                blank=True,
                help_text="Token used to register the channel (chat_id)",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Register token",
            ),
        ),
        migrations.AlterField(
            model_name="notificationconfig",
            name="register_token",
            field=models.CharField(
                blank=True,
                default=shargain.notifications.models.get_random_register_token,
                help_text="Token used to register the channel (chat_id)",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Register token",
            ),
        ),
    ]
