# Generated by Django 5.2.17 on 2026-09-24 14:49

from django.db import migrations

import shargain.commons.models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0006_notificationconfig_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationconfig",
            name="webhook_url",
            field=shargain.commons.models.HttpURLField(blank=True, verbose_name="Webhook url"),
        ),
    ]
